In [2]:
# Let's practice pooling
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# Create a simple 4x4 feature map
feature_map = torch.tensor([[
    [[-7, 2, -3, 5],
     [-6, 8, 1, 0],
     [4, -2, 9, 3],
     [-1, 7, -4, 6]]
]], dtype=torch.float32)


print("Original Feature Map:\n", feature_map[0,0])


Original Feature Map:
 tensor([[-7.,  2., -3.,  5.],
        [-6.,  8.,  1.,  0.],
        [ 4., -2.,  9.,  3.],
        [-1.,  7., -4.,  6.]])


# Max Pooling

In [3]:
max_pool = nn.MaxPool2d(kernel_size=2, stride=2)
pooled_max = max_pool(feature_map)

print("\nMax Pool Result:\n", pooled_max[0,0])


Max Pool Result:
 tensor([[8., 5.],
        [7., 9.]])


# Average Pooling


In [10]:

avg_pool = nn.AvgPool2d(kernel_size=2, stride=2)
pooled_avg = avg_pool(feature_map)

print("\nAverage Pool Result:\n", pooled_avg[0,0])


Average Pool Result:
 tensor([[-0.7500,  0.7500],
        [ 2.0000,  3.5000]])
